spring:
  cache:
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
    type: caffeine
  datasource:
    url: jdbc:simon:h2:mem:demodb;DB_CLOSE_DELAY=-1
    driver-class-name: org.javasimon.jdbc4.Driver
    username: sa
    password:
#    schema:
#      - classpath:sql/a.sql
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console

# http://localhost:8080/h2-console