INSERT INTO TBL_A (ID,NAME,DELETE_STATE,VERSION) VALUES (1,'huahua',0,0);
INSERT INTO TBL_A (ID,NAME,DELETE_STATE,VERSION) VALUES (2,'xixi',0,0);
INSERT INTO TBL_A (ID,NAME,DELETE_STATE,VERSION) VALUES (3,'caocao',0,0);
